### ISSUE TITLE
convertCellType Method for RasterSource

### ISSUE THREAD

**Issue by jbouffard** [geotrellis/geotrellis-contrib#114]
As of right now, there is now way to convert the `CellType` of a `RasterSource`. This is an issue, as the methods of `RasterSourceRDD` require that all `RasterSources` have the same `CellType`. For example: https://github.com/geotrellis/geotrellis-contrib/blob/master/vlm/src/main/scala/geotrellis/contrib/vlm/RasterSourceRDD.scala#L47-L48 By having a `convertCellType` method, it'll be possible to standardize all `RasterSource`s' `CellType`s.

**Comment by echeipesh** [comment]
Resolved by https://github.com/geotrellis/geotrellis-contrib/pull/126
