### ISSUE TITLE
Reprojection at (some) high zoom levels introduces nodata artifacts

### ISSUE THREAD

**Issue by jisantuc** [geotrellis/geotrellis-contrib#116]
## Problem Description

![image](https://user-images.githubusercontent.com/5702984/52581670-4ccb2880-2df9-11e9-9a60-7d338ede80d9.png)

For imagery in different parts of the world, somewhere between zooms 20 and 25 (so far), tiles come back from backsplash with a transparent 256th column. Removing the `.reproject` step [here](https://github.com/raster-foundry/raster-foundry/blob/develop/app-backend/backsplash-core/src/main/scala/com/rasterfoundry/backsplash/BacksplashImage.scala#L67) causes no transparent border to appear.

## Reproduction

- I'll send you a tif
- read the tif with the same strategy in the linked Raster Foundry code above at `/20/14562/509647/`
- (possibly necessary) render three bands (it doesn't seem to matter which) as a png
- observe the transparent right-most column

Avoiding unnecessary reprojection (#102) should help for WebMercator tiffs, but we see it with non-WM tiffs as well

**Comment by jisantuc** [comment]
Some other random information:

- single band renders are fine
- there's a pattern, where after the first zoom level, not all higher zoom levels show the seams

**Comment by pomadchin** [comment]
Actually this PR: https://github.com/locationtech/geotrellis/pull/2880 in geotrellis core fixes it. Won't close it until we get RasterSources working on some published gt artifact.

**Comment by pomadchin** [comment]
Restore this test https://github.com/geotrellis/geotrellis-contrib/pull/132 as the result.
