### ISSUE TITLE
Roll back to spark 2.3.x

### ISSUE THREAD

**Issue by metasim** [geotrellis/geotrellis-contrib#119]
We'd like to start using this library, but are stuck on spark 2.3.x for a while longer.

https://github.com/geotrellis/geotrellis-contrib/blob/be70b10e2e06b0e089d911164cad3e30f27abdb1/project/Dependencies.scala#L25

**Comment by pomadchin** [comment]
@metasim it's a provided dep https://github.com/geotrellis/geotrellis-contrib/blob/master/build.sbt#L68

We heavily depend on GeoTrellis 2.2 though and it was built against Spark 2.4.0. However it's also marked as provided in GeoTrellis. Probably you talk about some spark-sql issues (?)

**Comment by metasim** [comment]
@pomadchin Sorry about the shortness of description/context. @echeipesh and I are hammering out the next steps for RasterSource, and assuring Spark 2.3.x compatibility (and GT 2.2 compatibility) is a prerequisite for me to test out an integration in RasterFrames.

**Comment by pomadchin** [comment]
Ah right; I forgot that you're in Philly :partyparrot:

**Comment by echeipesh** [comment]
@metasim We did bump to spark 2.4 in GeoTrellis 2.2, something I should have checked yesterday:

https://github.com/locationtech/geotrellis/blob/7ef4daf1a913ba1e4daf017da0e2be50fb2b3797/project/Environment.scala#L24

I've been running some jobs on spark 2.3 with GT 2.2 and haven't run into binary compatibility problems. But the situation is usually more fragile with DataFrames. We could cut a version of GT 2.2 with Spark 2.3 dependency. I've been trying to avoid that kind of version spam on maven central but perhaps we can selectively publish to LT distribution repo.

**Comment by pomadchin** [comment]
I think that `spark-sql` dep can be more sensitive :/

**Comment by metasim** [comment]
@echeipesh As @pomadchin states, `spark-sql` is indeed where more breaking things appear to happen. That said, let's just leave things where they are and I'll try to put my paranoia to rest. If something crops up I'll either find a work-around or file another issue.
