### ISSUE TITLE
RasterSummary.estimatePartitionsNumber Produces an Unexpected Number of Partitions

### ISSUE THREAD

**Issue by jbouffard** [geotrellis/geotrellis-contrib#129]
[estimatePartitionsNumber](https://github.com/geotrellis/geotrellis-contrib/blob/master/vlm/src/main/scala/geotrellis/contrib/vlm/RasterSummary.scala#L38) is used when a `groupBy` occurs, and the user does not specify a `Partitioner`. This is a problem, however, as the number of partitions estimated can be very different from the input `RDD`'s partition count as can be seen below:

```
summary.estimatePartitionsNumber
res22: Int = 81

rasterRegionRDD.getNumPartitions
res23: Int = 1600
```
While there doesn't seem to be anything wrong with the logic in `estimatePartitionsNumber`, we might want to find a different to getting a partition number. Or at the very least, have a warning on that method explaining what could happen if a `Partitioner` is not passed.

**Comment by echeipesh** [comment]
Re-reading this issue it sounds like the potential problem is using the partition count from `estimatePartitionsNumber` to override the incoming RDD partitioning possibly in unhelpful way. I don't recall the context but likely the partition number suggested was way too low for the job.

This would be an issue any time `estimatePartitionsNumber` is used but specifically this probably refers to this instance:

https://github.com/geotrellis/geotrellis-contrib/blob/cc6b022d5f4ac1266b23962181d00cc9cce79e40/vlm/src/main/scala/geotrellis/contrib/vlm/spark/RasterSourceRDD.scala#L156

The only actionable suggestion I have is to take the max of the existing partition count and suggested partition count, assuming that a larger partition count represents some kind of user optimization.
