### ISSUE TITLE
RasterSource generates RasterRegions to cover it

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-contrib#131]
Use Case: Generate list of `RasterRegion` to cover RasterSource at its own resolution, projection.

This would be useful if you wanted to split up a large raster and shuffle the `RasterRegion` s for intersection. Currently the only way to generate the regions is using `LayoutTileSource` which requires a `LayoutDefinition`.

**Comment by metasim** [comment]
@echeipesh Probably obvious, but here's how I'm approaching this in RasterFrames:

https://github.com/s22s/rasterframes/blob/cb77ca171e237f4db20dc92b336c062a5647543b/core/src/main/scala/astraea/spark/rasterframes/ref/RasterSource.scala#L72-L74

**Comment by echeipesh** [comment]
Currently this functionality is generally covered by `LayoutTileSource` and specifically:

https://github.com/geotrellis/geotrellis-contrib/blob/aca902c5c9ff8e37169b6e8f95bc22decf7ae5e2/vlm/src/main/scala/geotrellis/contrib/vlm/LayoutTileSource.scala#L155-L161

There are other ways in which working with `RasterRegion` is currently not supported and would be helpful but this issue doesn't speak to that so I'm closing it to be replaced by more specific wants in the future.
