### ISSUE TITLE
Add support for Tags in RasterSource

### ISSUE THREAD

**Issue by metasim** [geotrellis/geotrellis-contrib#143]
Raster metadata is very important to many forms of processing. Providing a means of passing that information up from the `RasterSource` is desirable. In lieu of the "right" solution, I'd suggest in the short term just using `geotrellis.raster.io.geotiff.Tags`, perhaps  type aliased if you want the import included with the core library.

How it's currently being handled in RasterFrames:

https://github.com/s22s/rasterframes/blob/ac41b3629fce29912790ddce923967591de0c746/core/src/main/scala/astraea/spark/rasterframes/ref/RasterSource.scala#L246

https://github.com/s22s/rasterframes/blob/ac41b3629fce29912790ddce923967591de0c746/core/src/main/scala/astraea/spark/rasterframes/ref/RasterSource.scala#L175-L178

**Comment by metasim** [comment]
@pomadchin 
As of `0.10.2` our workaround of accessing the `dataset` member in the swig bindings has gone away:

```scala
   private def metadata =
      gdal.dataset
        .GetMetadata_Dict()
        .asInstanceOf[java.util.Dictionary[String, String]]
        .asScala
        .toMap
```

Any thoughts on how to get at the metadata tags now?

**Comment by pomadchin** [comment]
@metasim it is not supported now, can you create an issue in a gdal bindings repo?

**Comment by pomadchin** [comment]
for the context: we are not going to return back to the swig gdal bindings.

**Comment by metasim** [comment]
@pomadchin Should there be an unified API for tags across all `RasterSource`s?

Didn't mean to imply any kind of swig gdal rollback.... just trying to share our use cases. If these issues are a distraction let me know and I'll stop filing them.

**Comment by pomadchin** [comment]
Nope, keep doing it! We were focused to make a fast IO for the RF case, so feel free to write any of your thoughts! Yep, probably the API should be as much unified as it is possible

**Comment by metasim** [comment]
https://github.com/geotrellis/geotrellis-contrib/issues/99

**Comment by pomadchin** [comment]
The issue was addressed here: https://github.com/geotrellis/gdal-warp-bindings/issues/33 
However, probably we need to expose it via contrib API.

**Comment by metasim** [comment]
@echeipesh Per this and #99, do you have opinions on how metadata might be exposed in RasterSource in a way that cross-cuts multiple back-ends? GDAL has the concept of "domains" that the others don't, and the Avro ones are super free-form if memory serves.

**Comment by pomadchin** [comment]
closed in https://github.com/geotrellis/geotrellis-contrib/pull/216
