### ISSUE TITLE
Add Effect Type for Raster Sources

### ISSUE THREAD

**Issue by notthatbreezy** [geotrellis/geotrellis-contrib#162]
Raster sources act as though all operations are synchronous right now - e.g. reads, reprojections, etc. This is not fully accurate and it makes optimizing some things inside the library, for instance gathering metadata on a mosaic raster source with many underlying data sources difficult. Additionally, when integrating with application code care has to be taken to properly wrap raster source methods with an effect to manage multithreading behavior. Adding an effect type would go a long way to making these two things easier I think.

**Comment by jisantuc** [comment]
Based on geotrellis/maml#101, this shouldn't maybe be all that painful:

https://github.com/geotrellis/maml/pull/101/commits/1d5ec93fc02723514d19a33bb627878504eca404

`cats`' `Id` type is a one type parameter functor / monad that doesn't require any changes to contained code, so `RasterSource[F[_]]` could have a default implementation of `RasterSource[Id]` and effectful implementations with `RasterSource[F[_]: Sync]` or whatever we think is the most appropriate constraint

**Comment by pomadchin** [comment]
@jisantuc I've prototyped smth similar to what you suggest: https://github.com/pomadchin/geotrellis-contrib/commit/249aa164437045f32803b987a85ad4c584e0f3e4

However I think that `Sync` is a too restrictive API. Probably we'd have to come up with smth better. 
I want to prototype another version that will be effect agnostic as well but will use less restrictive bounds that will allow users to use it in a more flexible way:
For instance: what if we want sometimes to have `Async` API? What if there would be `Async` reads / user would like to implement an `Async` interface. Mb they want to incapsulate shifting logic into their classes or mb not.

**Comment by jisantuc** [comment]
I didn't know! Yeah I'm not trying to argue for `Sync` in particular. We might even just leave it at `Monad` and let users get more specific if they feel like it -- I only meant to point out that we don't have to demand any effectfulness from the parameterized type to add an `F[_]` to `RasterSource`, since we can provide an ignorant-about-effect default through `Id`

**Comment by pomadchin** [comment]
@jisantuc Good pointer :+1: though I would like to try an approach with adding our own type classes like `ReadGeoTiff[F[_]]`, `ReadGDAL[F[_]]`, `ReadGeoTrellis[F[_]]` so it would be much easier for users to override logic :/ But I haven't prototyped it yet to compare with the current prototype I pointed you on ):
