### ISSUE TITLE
Improve error reporting in GDALDataset

### ISSUE THREAD

**Issue by metasim** [geotrellis/geotrellis-contrib#179]
Reporting of errors from the JNI bindings could easily be improved. Currently they take the form of:

https://github.com/geotrellis/geotrellis-contrib/blob/94ccdebff8ce58f5f3d8e1f96046961bb6ba1a46/gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala#L148

 in the following ways:

1. Don't throw top-level `Exception`, but something more "filterable", such as `IOException`, `ConnectException` or a new custom `GDALException`.
2. Setting the message to be the name of the JNI method doesn't provide enough information to figure out what happened. First order would be to include the integer error code.
3. Even better would be to convert the error code via a lookup table into something user interpretable. e.g. "403 authorization error".

**Comment by jbouffard** [comment]
After looking to see [where Exceptions are thrown](https://github.com/geotrellis/geotrellis-contrib/search?p=1&q=Exception&unscoped_q=Exception) it seems like there aren't too many places where it occurs. Because of that, I'm not sure if we really need error codes because most of the exceptions are only thrown in one place.

**Comment by pomadchin** [comment]
Hey @jbouffard, in this particular issue @metasim means that all exceptions thrown [here](https://github.com/geotrellis/geotrellis-contrib/blob/master/gdal/src/main/scala/geotrellis/contrib/vlm/gdal/GDALDataset.scala) should be more readable and the type should be more specific. At the moment GDAL bindings don't forward exception error codes / etc, but we can think of them to make the exceptions a bit more human readable.

**Comment by jbouffard** [comment]
@pomadchin Ah, okay. That makes a bit more sense.

**Comment by metasim** [comment]
To be clear, what I meant by "error codes" are the classifications outlined in here:

https://joinup.ec.europa.eu/svn/gvsig-3d/1.10/trunk/binaries/mac/raster/gdal/GDAL.framework/Versions/1.7/Resources/doc/gdal/cpl__error_8h.html
