### ISSUE TITLE
VSIPath inconsistent behavior

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-contrib#191]
For the context, originally we were copying a [RasterIO behavior](https://github.com/mapbox/rasterio/blob/960a906dad2a4e426387ce048a52c6e90afdcd2b/tests/test_path.py).

The example of our tests are here [https://github.com/geotrellis/geotrellis-contrib/blob/master/gdal/src/test/scala/geotrellis/contrib/vlm/gdal/VSIPathSpec.scala#L59-L73]. 

The question is: why do we add `visgzip` prefix automatically, guessing about it from the file extension and we don't do the same way with `zip` extension: 

```scala
it("http that points to gz with ! url") {
  val filePath = "www.radomdata.com/test-files/data.gz"
  val url = s"http://$filePath!$fileName"
  val expectedPath = s"/vsigzip//vsicurl/http://$filePath/$fileName"

  VSIPath(url).vsiPath should be (expectedPath)
}

it("zip+http url") {
  val filePath = "www.radomdata.com/test-files/data.zip"
  val url = s"zip+http://$filePath"
  val expectedPath = s"/vsizip//vsicurl/$url"

  VSIPath(url).vsiPath should be (expectedPath)
}
```

It makes sense to choose one approach and follow it, to avoid such an inconsistent VSIParser behavior.

Edit: 

I also noticed this test case:

```scala
it("file that points to zip with ! uri") {
  val filePath = "/home/jake/Documents/test-files/files.zip"
  val uri = s"file://$filePath!$fileName"
  val expectedPath = s"/vsizip/$filePath/$fileName"

  VSIPath(uri).vsiPath should be (expectedPath)
}
```

It means, that `zip+` prefix is not necessary at all. Should we keep it then? What are your thoughts about the implicit `vsizip/vsigzip` application?

**Comment by moradology** [comment]
Assuming this strategy doesn't fall on its face or have tons of edge cases, I'd be in favor of inferring the correct `vsi` url based on extensions

**Comment by pomadchin** [comment]
But as @jpolchlo noticed, this is not always the truth or mb not always you need to unpack your archive to read some metadata that is stored in the same dir.

**Comment by jbouffard** [comment]
@pomadchin I'm not sure if the behavior is inconsistent, because those two tests your linked to cover different things. The first one tests the behavior of reading a file from a `gzip` container (hence the `!`), while the latter is about just reading the zip the file itself. Also, the `gzip+` prefix is optional when reading the whole compressed file. As an example:

```
scala> val t1 = "http://www.random.com/path/to/zipped/files.gz"
t1: String = http://www.random.com/path/to/zipped/files.gz

scala> val t2 = "gz+http://www.random.com/path/to/zipped/files.gz"
t2: String = gz+http://www.random.com/path/to/zipped/files.gz

scala> GDALDataPath(t1)
res0: geotrellis.contrib.vlm.gdal.GDALDataPath = http://www.random.com/path/to/zipped/files.gz

scala> GDALDataPath(t1).vsiPath
res1: String = /vsigzip//vsicurl/http://www.random.com/path/to/zipped/files.gz

scala> GDALDataPath(t2).vsiPath
res2: String = /vsigzip//vsicurl/gz+http://www.random.com/path/to/zipped/files.gz
```

**Comment by jbouffard** [comment]
Ah, I take that back. It looks like there is a slight inconsistency in behavior.

**Comment by moradology** [comment]
We should probably just defer to the existing implementations on pain of having to explain our well-thought-out-reasons for diverging

**Comment by pomadchin** [comment]
A rasterio behaviour:

```python
>>> vsi_path(parse_path('s3://tests/data/files.zip!foo.tif'))
'/vsis3/tests/data/files.zip/foo.tif'
>>> vsi_path(parse_path('zip+s3://tests/data/files.zip!foo.tif'))
'/vsizip/vsis3/tests/data/files.zip/foo.tif'
```

Our behavior: 

```scala
GDALDataPath("s3://tests/data/files.zip!foo.tif").vsiPath
// res0: String = /vsizip//vsis3/tests/data/files.zip/foo.tif
GDALDataPath("zip+s3://tests/data/files.zip!foo.tif").vsiPath
// res1: String = /vsizip//vsis3/tests/data/files.zip/foo.tif
```

**Comment by pomadchin** [comment]
I thought about it a little bit more, we can support both syntaxes for sure. But what if we have nofile extension, or the extension is incorrect? 

An example of the current incorrect behavior:
```scala
GDALDataPath("s3://tests/data/files!foo.tif").vsiPath
// res0: String = /vsis3/tests/data/files/foo.tif
GDALDataPath("zip+s3://tests/data/files!foo.tif").vsiPath
// res1: String = /vsis3/tests/data/files/foo.tif
```
