### ISSUE TITLE
Use scala-uri library to parse VSIPath

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-contrib#192]
Tight now we have lot's of weirdly implemented regexps, we can replace them by a lightweight [scala-uri](https://github.com/lemonlabsuk/scala-uri) library.

```scala
import io.lemonlabs.uri.{Url, UrlWithAuthority}

val fileName = "file-1.tiff"

val filePath = "www.radomdata.com/test-files/file-1.tiff"
val url = s"http://$filePath"
val httpUrl = UrlWithAuthority.parse(url)
httpUrl.schemeOption
httpUrl.hostOption
httpUrl.path
httpUrl.authority

val zipPath = "www.radomdata.com/test-files/data.zip"
val zipURL = s"zip+http://$zipPath"
val zipUrl = UrlWithAuthority.parse(zipURL)
zipUrl.schemeOption
zipUrl.hostOption
zipUrl.path
zipUrl.authority
```

It is also serializable, covered with tests, doesn't bring any really new deps (only a parbolied parser) and will help us to make the code more readable.

**Comment by jbouffard** [comment]
This issue should be addressed once #188 is merged.
