### ISSUE TITLE
Mosaic Raster Source Causes Clipping/Extent Issues

### ISSUE THREAD

**Issue by notthatbreezy** [geotrellis/geotrellis-contrib#207]
Previously we had an issue with tiles being clipped for MosaicRasterSource that manifested as a problem in WMS for geotrellis-server. https://github.com/geotrellis/geotrellis-contrib/pull/202 was opened to try and fix this issue and added a test for it as well.

However, the problem still manifests itself when setting the tile size for WMS:

![image](https://user-images.githubusercontent.com/898060/60989896-1c8aa600-a315-11e9-940f-ce764221b6c4.png)

Additionally (and this seems related) we noticed that if tile size is not set the extent/placement of the _single_ tile moves based on map queries. It seems that if the top left of the requested area is _inside_ the extent of the source imagery then the requested tile is correct. If the top-left of the imagery is _outside_ the source imagery then the requested area moves and aligns itself incorrectly.

![image](https://user-images.githubusercontent.com/898060/60990068-90c54980-a315-11e9-9a08-5d285b6a3ec3.png)

![image](https://user-images.githubusercontent.com/898060/60990075-9327a380-a315-11e9-8764-830b774044e0.png)

**Comment by pomadchin** [comment]
@notthatbreezy is it possible to create a unit test?

**Comment by notthatbreezy** [comment]
Note: this https://github.com/geotrellis/geotrellis-contrib/pull/202/commits/4d7a595685064e6f45ce6ead63934ea4a61898fa _fixed_ the problem and had the tests pass, but the test wasn't sufficient to fix this use-case.

**Comment by moradology** [comment]
@pomadchin Looking for more info right now to reproduce via tests

**Comment by notthatbreezy** [comment]
@pomadchin - I don't have a unit test to replicate this bad behavior -- the one from before was insufficient to solve this problem. I suppose it _could_ be a problem in gt-server, but it isn't 100 percent clear. @moradology is working on tracking this down

**Comment by moradology** [comment]
This issue connects up with RF issue [4965](https://github.com/raster-foundry/raster-foundry/issues/4965)

**Comment by moradology** [comment]
Spent ~2points on this, so far, but I think we've got a good-enough answer (for now): https://github.com/raster-foundry/raster-foundry/pull/5077
