### ISSUE TITLE
Upgrade dependencies

### ISSUE THREAD

**Issue by jisantuc** [geotrellis/geotrellis-contrib#233]
Version 0.11.1 isn't binary compatible with 0.9.1. If a newer project decides to use pureconfig, they'll probably pick the newest version (I just did), and it takes a small but still low-key annoying quantity of effort to figure out where `java.lang.NoSuchMethodError: pureconfig.ConfigReader$.traversableReader(Lpureconfig/Derivation;Lscala/collection/generic/CanBuildFrom;)Lpureconfig/ConfigReader` is coming from

**Comment by pomadchin** [comment]
Let's make it a more generic task: update all deps before the RC1?

**Comment by jisantuc** [comment]
Sensible -- might be easiest to do this by setting up scala steward, which is some work we think we should also do in RF

**Comment by pomadchin** [comment]
Well, in our case it won't help ): we'll have to file CQs ourselves, and this is the problem rather than bumping up deps versions.
