### ISSUE TITLE
Free GDAL related resources

### ISSUE THREAD

**Issue by pomadchin** [geotrellis/geotrellis-contrib#36]
We can consider https://github.com/jsuereth/scala-arm library usage as suggested @echeipesh to work better with resources that should be closed.

**Comment by pomadchin** [comment]
I looked into this project, and basically it implements smth like this: https://github.com/locationtech/geotrellis/blob/f8af6e6d72749b8fb175a0c44cbc7d027a940686/cassandra/src/main/scala/geotrellis/spark/io/cassandra/CassandraInstance.scala#L76 but in a more generic fashion. Wondering should this logic be incapsulated somehow into our API or that should be smth used on the user side. It sounds like it should be a part of our API, but it can make it's usage a bit more complicated.

**Comment by pomadchin** [comment]
@echeipesh mentioned this article during the RRP: https://medium.com/@dkomanov/scala-try-with-resources-735baad0fd7d

**Comment by pomadchin** [comment]
@moradology suggested also to try https://typelevel.org/cats-effect/datatypes/resource.html this can be actually pretty good if we'll decide to work with IO interface.

**Comment by echeipesh** [comment]
The API here is intentionally bare and simple. Clearly now `GDALRasterSource` needs to be managed, which is currently a client concern. `scala-arm` is simple and direct way to work around this problem in client code though if they/we so choose.

As work from `geotrellis-server` progresses we may decide to shift some of the async facilities into core `geotrellis-contrib-vlm` project. Probably at that point we're going to use `Resource[F[_]]`.
