### ISSUE TITLE
Collecting Metadata From a Generic, Reprojected RasterSource

### ISSUE THREAD

**Issue by jbouffard** [geotrellis/geotrellis-contrib#40]
I've come across an issue when collecting metadata from an `RDD` that contains some reprojected `RasterSource`(s). The problem is that when reprojecting an `RDD` of either `GDALRasterSource`(s) or `GeoTiffRasterSource`(s) the resulting `RDD`'s `RasterSource`(s) don't have the appropriate `CRS`.

For example, this is some of the code that I'm running:

```scala
    val rasterSourceRDD: RDD[RasterSource] =
      (readMethod match {
        case GEOTRELLIS => rdd.map { new GeoTiffRasterSource(_): RasterSource }
        case GDAL => rdd.map { GDALRasterSource(_): RasterSource }
      }).cache()

    val reprojectedSourcesRDD: RDD[RasterSource] =
      targetCRS match {
        case crs: String =>
          rasterSourceRDD.map { _.reproject(CRS.fromString(crs), resampleMethod) }
        case null =>
          rasterSourceRDD
      }

    val metadata: RasterSummary = RasterSummary.fromRDD(reprojectedSourcesRDD)

    println(s"\nThis is the targetCRS: $targetCRS")
    println(s"This is the crs of the metadata: ${metadata.crs}\n")
```

And these were the values that were printed:

```
This is the targetCRS: +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext +no_defs 

This is the crs of the metadata: merc-CS
```

**Comment by pomadchin** [comment]
@jbouffard what would happen if you print both as proj4 strings?

**Comment by jbouffard** [comment]
@pomadchin Ah, doing that shows they're the same. Hmm... I guess my tests are failing for a different reason then. Thanks for suggesting I try that.

**Comment by pomadchin** [comment]
@jbouffard yes, the difference you saw was due to the thing that `targetCRS` is a proj4 string, and in the second print you used crs.toString which is crs.name by default.
