### ISSUE TITLE
Passing -oo options to GDALRasterSource

### ISSUE THREAD

**Issue by echeipesh** [geotrellis/geotrellis-contrib#65]
```scala
scala> val rs = GDALRasterSource("/vsigzip//vsis3/elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz")
rs: geotrellis.contrib.vlm.gdal.GDALRasterSource = GDALRasterSource(/vsigzip//vsis3/elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz,true)

scala> rs.extent
ERROR 1: DoSinglePartPUT of /vsis3/elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz.properties failed
geotrellis.contrib.vlm.gdal.GDALException: GDAL ERROR 1: DoSinglePartPUT of /vsis3/elevation-tiles-prod/v2/skadi/N89/N89E179.hgt.gz.properties failed
  at geotrellis.contrib.vlm.gdal.GDALException$.lastError(GDAL.scala:42)
  at geotrellis.contrib.vlm.gdal.GDAL$.openPath(GDAL.scala:65)
  at geotrellis.contrib.vlm.gdal.GDAL$.open(GDAL.scala:53)
  at geotrellis.contrib.vlm.gdal.GDAL$$anonfun$3.apply(GDAL.scala:95)
  at geotrellis.contrib.vlm.gdal.GDAL$$anonfun$3.apply(GDAL.scala:87)
```

This is because of: https://github.com/OSGeo/gdal/blob/be692ceb73ba18355bdfbad1a0ced16c641bbfe7/gdal/doc/gdal_virtual_file_systems.dox#L173-L176

> When the file is located in a writable location, a file with extension .gz.properties
is created with an indication of the uncompressed file size (the creation of that
file can be disabled by setting the CPL_VSIL_GZIP_WRITE_PROPERTIES configuration
option to NO).

`man gdalwarp` release these are passed through `[-oo NAME=VALUE]*`

**Comment by pomadchin** [comment]
We'll have to support all WarpOptions / common options finally

**Comment by pomadchin** [comment]
Fixed here: https://github.com/geotrellis/geotrellis-gdal/pull/24/files#diff-27d71395a6232fcbb11016caa62b9141R147
