### ISSUE TITLE
Can't create raster sources from imagery outside default region

### ISSUE THREAD

**Issue by jisantuc** [geotrellis/geotrellis-contrib#70]
`GeoTiffRasterSource`s and anything else that use `getByteReader` can only read imagery from a single region:

https://github.com/geotrellis/geotrellis-contrib/blob/2cd6431ef60a03df040848591f8f1bf141d4f6d3/vlm/src/main/scala/geotrellis/contrib/vlm/package.scala#L50

since they all use the default s3 client.

That's a drag if you want to read imagery where you don't know the source region in advance, or if imagery is provided by users and could live anywhere.

**Comment by pomadchin** [comment]
Closed here https://github.com/geotrellis/geotrellis-contrib/pull/71
